In [1]:
import pandas as pd

In [2]:
import pdfplumber
import pandas as pd
import re
from pathlib import Path

print("PDF extraction tools ready")

PDF extraction tools ready

In [3]:
sales_pdf = Path("../data/raw/sales_history.pdf")
inventory_pdf = Path("../data/raw/inventory_count.pdf")

print(sales_pdf.exists())
print(inventory_pdf.exists())

True
True

In [4]:
with pdfplumber.open(sales_pdf) as pdf:
    first_page_text = pdf.pages[0].extract_text()

print(first_page_text[:2000])

(cid:27)(cid:13)Run Date: 06/24/26 Page# 1
S A L E S H I S T O R Y
By Detail Inventory
Tx# Inventory# Description Cases Kegs Other Price Cost Total Price Total Cost Gross Profit CAT Pd
-------- ------------ ------------------------- ------ ------ ------ ------- ------- ------------ ------------ ------------ ------
194142 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
194944 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
196770 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
199190 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
4 0 0 69.96 54.60 15.36 22.0%
197536 00207 LITE 7OZ NR CASE 2 20.99 16.65 41.98 33.30 8.68 001 05
198152 00207 LITE 7OZ NR CASE 1 20.99 16.65 20.99 16.65 4.34 001 05
3 0 0 62.97 49.95 13.02 20.7%
197364 30007 HEINEKEN 7NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195653 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
195784 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
196770 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
3 0 0 64.77 50.40 14.37 22.2%
194376 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
194788 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195148 59080 CORONA 7OZ NR CASE 2 29.59 22.40 59.18 44.80 14.38 001 05
195414 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195653 59080 CORONA 7OZ NR CASE 1 25.15 22.40 25.15 22.40 2.75 001 05
195784 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195911 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
196101 59080 CORONA 7OZ NR CASE 1 25.15 22.40 25.15 22.40 2.75 001 05
197749 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
198765 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
199571 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
12 0 0 346.20 268.80 77.40 22.4%
196473 9405 STELLA ARTOIS 7NR CASE 1 29.99 23.95 29.99 23.95 6.04 00

In [5]:
all_sales_text = ""

with pdfplumber.open(sales_pdf) as pdf:
    print("Number of pages:", len(pdf.pages))
    
    for page in pdf.pages:
        text = page.extract_text()
        if text:
            all_sales_text += text + "\n"

print(all_sales_text[:1000])

Number of pages: 182
(cid:27)(cid:13)Run Date: 06/24/26 Page# 1
S A L E S H I S T O R Y
By Detail Inventory
Tx# Inventory# Description Cases Kegs Other Price Cost Total Price Total Cost Gross Profit CAT Pd
-------- ------------ ------------------------- ------ ------ ------ ------- ------- ------------ ------------ ------------ ------
194142 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
194944 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
196770 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
199190 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
4 0 0 69.96 54.60 15.36 22.0%
197536 00207 LITE 7OZ NR CASE 2 20.99 16.65 41.98 33.30 8.68 001 05
198152 00207 LITE 7OZ NR CASE 1 20.99 16.65 20.99 16.65 4.34 001 05
3 0 0 62.97 49.95 13.02 20.7%
197364 30007 HEINEKEN 7NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195653 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
195784 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 2

In [6]:
sales_lines = all_sales_text.split("\n")

print("Total lines:", len(sales_lines))
print("First 20 lines:")
for line in sales_lines[:20]:
    print(line)

Total lines: 9278
First 20 lines:
(cid:27)(cid:13)Run Date: 06/24/26 Page# 1
S A L E S H I S T O R Y
By Detail Inventory
Tx# Inventory# Description Cases Kegs Other Price Cost Total Price Total Cost Gross Profit CAT Pd
-------- ------------ ------------------------- ------ ------ ------ ------- ------- ------------ ------------ ------------ ------
194142 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
194944 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
196770 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
199190 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
4 0 0 69.96 54.60 15.36 22.0%
197536 00207 LITE 7OZ NR CASE 2 20.99 16.65 41.98 33.30 8.68 001 05
198152 00207 LITE 7OZ NR CASE 1 20.99 16.65 20.99 16.65 4.34 001 05
3 0 0 62.97 49.95 13.02 20.7%
197364 30007 HEINEKEN 7NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195653 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
195784 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
196770 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
3 0 0 64.77 50.40 14.37 22.2%
194376 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
194788 59080 CORONA 7OZ NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05

In [7]:
transaction_lines = []

for line in sales_lines:
    line = line.strip()
    

    if re.match(r"^\d{6}\s+", line):
        transaction_lines.append(line)

print("Transaction lines found:", len(transaction_lines))
print("First 10 transaction lines:")

for line in transaction_lines[:10]:
    print(line)

Transaction lines found: 7136
First 10 transaction lines:
194142 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
194944 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
196770 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
199190 00107 HIGH LIFE 7OZ NR CASE 1 17.49 13.65 17.49 13.65 3.84 001 05
197536 00207 LITE 7OZ NR CASE 2 20.99 16.65 41.98 33.30 8.68 001 05
198152 00207 LITE 7OZ NR CASE 1 20.99 16.65 20.99 16.65 4.34 001 05
197364 30007 HEINEKEN 7NR CASE 1 29.59 22.40 29.59 22.40 7.19 001 05
195653 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
195784 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05
196770 35907 COORS LIGHT 7OZ NR CASE 1 21.59 16.80 21.59 16.80 4.79 001 05

In [8]:
sales_rows = []

for line in transaction_lines:
    parts = line.split()
    
    tx_number = parts[0]
    inventory_number = parts[1]
    
    
    cases = parts[-9]
    kegs = parts[-8]
    other = parts[-7]
    price = parts[-6]
    cost = parts[-5]
    total_price = parts[-4]
    total_cost = parts[-3]
    gross_profit = parts[-2]
    category = parts[-1]
    

    description = " ".join(parts[2:-9])
    
    sales_rows.append({
        "tx_number": tx_number,
        "inventory_number": inventory_number,
        "description": description,
        "cases": cases,
        "kegs": kegs,
        "other": other,
        "price": price,
        "cost": cost,
        "total_price": total_price,
        "total_cost": total_cost,
        "gross_profit": gross_profit,
        "category": category
    })

sales_df = pd.DataFrame(sales_rows)

sales_df.head()

,tx_number,inventory_number,description,cases,kegs,other,price,cost,total_price,total_cost,gross_profit,category
0,194142,00107,HIGH LIFE 7OZ NR,CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
1,194944,00107,HIGH LIFE 7OZ NR,CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
2,196770,00107,HIGH LIFE 7OZ NR,CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
3,199190,00107,HIGH LIFE 7OZ NR,CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
4,197536,00207,LITE 7OZ NR,CASE,2,20.99,16.65,41.98,33.30,8.68,001,05

In [9]:
numeric_columns = [
    "cases", "kegs", "other", "price", "cost",
    "total_price", "total_cost", "gross_profit"
]

for col in numeric_columns:
    sales_df[col] = pd.to_numeric(sales_df[col], errors="coerce")

sales_df["profit_margin"] = sales_df["gross_profit"] / sales_df["total_price"]

sales_df.head()

,tx_number,inventory_number,description,cases,kegs,other,price,cost,total_price,total_cost,gross_profit,category,profit_margin
0,194142,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.07326
1,194944,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.07326
2,196770,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.07326
3,199190,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.07326
4,197536,00207,LITE 7OZ NR,NaN,2,20.99,16.65,41.98,33.30,8.68,1,05,0.03003

In [10]:
print("Rows:", len(sales_df))
print("Total Revenue:", sales_df["total_price"].sum())
print("Total Gross Profit:", sales_df["gross_profit"].sum())
print("Total Cases:", sales_df["cases"].sum())

sales_df.describe()

Rows: 7136
Total Revenue: 179261.73
Total Gross Profit: 133388
Total Cases: 5743.6

,cases,kegs,other,price,cost,total_price,total_cost,gross_profit,profit_margin
count,784.000000,7136.000000,7106.000000,6917.000000,7126.000000,6909.000000,7136.000000,7136.000000,6909.000000
mean,7.326020,1.955297,21.492391,16.094872,32.285039,25.946118,7.119039,18.692265,2.890262
std,6.244373,3.992824,25.795663,18.230253,91.255630,37.384180,77.940390,21.485329,9.404087
min,1.000000,-4.000000,-100.000000,0.010000,-3516.000000,-128.000000,-3516.000000,1.000000,-3.367003
25%,1.000000,1.000000,10.590000,7.120000,12.880000,8.880000,3.790000,8.000000,0.296296
50%,6.000000,1.000000,18.990000,13.480000,21.990000,15.800000,5.990000,10.000000,0.613497
75%,12.000000,2.000000,25.990000,20.000000,38.990000,29.700000,9.680000,19.000000,2.255639
max,24.000000,156.000000,791.000000,320.000000,709.800000,504.000000,520.000000,127.000000,142.857143

In [11]:
sales_df.head(10)

,tx_number,inventory_number,description,cases,kegs,other,price,cost,total_price,total_cost,gross_profit,category,profit_margin
0,194142,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.073260
1,194944,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.073260
2,196770,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.073260
3,199190,00107,HIGH LIFE 7OZ NR,NaN,1,17.49,13.65,17.49,13.65,3.84,1,05,0.073260
4,197536,00207,LITE 7OZ NR,NaN,2,20.99,16.65,41.98,33.30,8.68,1,05,0.030030
5,198152,00207,LITE 7OZ NR,NaN,1,20.99,16.65,20.99,16.65,4.34,1,05,0.060060
6,197364,30007,HEINEKEN 7NR,NaN,1,29.59,22.40,29.59,22.40,7.19,1,05,0.044643
7,195653,35907,COORS LIGHT 7OZ NR,NaN,1,21.59,16.80,21.59,16.80,4.79,1,05,0.059524
8,195784,35907,COORS LIGHT 7OZ NR,NaN,1,21.59,16.80,21.59,16.80,4.79,1,05,0.059524
9,196770,35907,COORS LIGHT 7OZ NR,NaN,1,21.59,16.80,21.59,16.80,4.79,1,05,0.059524

In [12]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7136 entries, 0 to 7135
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tx_number         7136 non-null   str
 1   inventory_number  7136 non-null   str
 2   description       7136 non-null   str
 3   cases             784 non-null    float64
 4   kegs              7136 non-null   int64
 5   other             7106 non-null   float64
 6   price             6917 non-null   float64
 7   cost              7126 non-null   float64
 8   total_price       6909 non-null   float64
 9   total_cost        7136 non-null   float64
 10  gross_profit      7136 non-null   int64
 11  category          7136 non-null   str
 12  profit_margin     6909 non-null   float64
dtypes: float64(7), int64(2), str(4)
memory usage: 724.9 KB

In [13]:
sales_rows = []

for line in transaction_lines:
    parts = line.split()

    tx_number = parts[0]
    inventory_number = parts[1]

    pd_period = parts[-1]
    category = parts[-2]
    gross_profit = parts[-3]
    total_cost = parts[-4]
    total_price = parts[-5]
    cost = parts[-6]
    price = parts[-7]

  
    before_price = parts[2:-7]


    quantity = before_price[-1]
    description = " ".join(before_price[:-1])

    sales_rows.append({
        "tx_number": tx_number,
        "inventory_number": inventory_number,
        "description": description,
        "quantity_sold": quantity,
        "price": price,
        "cost": cost,
        "total_price": total_price,
        "total_cost": total_cost,
        "gross_profit": gross_profit,
        "category": category,
        "period": pd_period
    })

sales_df = pd.DataFrame(sales_rows)

sales_df.head(10)

,tx_number,inventory_number,description,quantity_sold,price,cost,total_price,total_cost,gross_profit,category,period
0,194142,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
1,194944,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
2,196770,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
3,199190,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05
4,197536,00207,LITE 7OZ NR CASE,2,20.99,16.65,41.98,33.30,8.68,001,05
5,198152,00207,LITE 7OZ NR CASE,1,20.99,16.65,20.99,16.65,4.34,001,05
6,197364,30007,HEINEKEN 7NR CASE,1,29.59,22.40,29.59,22.40,7.19,001,05
7,195653,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05
8,195784,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05
9,196770,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05

In [14]:
numeric_cols = [
    "quantity_sold",
    "price",
    "cost",
    "total_price",
    "total_cost",
    "gross_profit"
]

for col in numeric_cols:
    sales_df[col] = pd.to_numeric(sales_df[col], errors="coerce")

sales_df["profit_margin"] = sales_df["gross_profit"] / sales_df["total_price"]

sales_df.head(10)

,tx_number,inventory_number,description,quantity_sold,price,cost,total_price,total_cost,gross_profit,category,period,profit_margin
0,194142,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05,0.219554
1,194944,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05,0.219554
2,196770,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05,0.219554
3,199190,00107,HIGH LIFE 7OZ NR CASE,1,17.49,13.65,17.49,13.65,3.84,001,05,0.219554
4,197536,00207,LITE 7OZ NR CASE,2,20.99,16.65,41.98,33.30,8.68,001,05,0.206765
5,198152,00207,LITE 7OZ NR CASE,1,20.99,16.65,20.99,16.65,4.34,001,05,0.206765
6,197364,30007,HEINEKEN 7NR CASE,1,29.59,22.40,29.59,22.40,7.19,001,05,0.242987
7,195653,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05,0.221862
8,195784,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05,0.221862
9,196770,35907,COORS LIGHT 7OZ NR CASE,1,21.59,16.80,21.59,16.80,4.79,001,05,0.221862

In [15]:
print("Rows:", len(sales_df))
print("Total Revenue:", sales_df["total_price"].sum())
print("Total Gross Profit:", sales_df["gross_profit"].sum())
print("Total Quantity Sold:", sales_df["quantity_sold"].sum())

sales_df.describe()

Rows: 7136
Total Revenue: 230063.19000000003
Total Gross Profit: 50801.46000000001
Total Quantity Sold: 13953

,quantity_sold,price,cost,total_price,total_cost,gross_profit,profit_margin
count,7136.000000,7106.000000,6917.000000,7126.000000,6909.000000,7136.000000,7126.000000
mean,1.955297,21.492391,16.094872,32.285039,25.946118,7.119039,0.240460
std,3.992824,25.795663,18.230253,91.255630,37.384180,77.940390,2.172610
min,-4.000000,-100.000000,0.010000,-3516.000000,-128.000000,-3516.000000,-75.923077
25%,1.000000,10.590000,7.120000,12.880000,8.880000,3.790000,0.225750
50%,1.000000,18.990000,13.480000,21.990000,15.800000,5.990000,0.283834
75%,2.000000,25.990000,20.000000,38.990000,29.700000,9.680000,0.332717
max,156.000000,791.000000,320.000000,709.800000,504.000000,520.000000,1.000000

In [16]:
sales_df.to_csv("../exports/clean_sales.csv", index=False)

print("Sales data exported successfully!")

Sales data exported successfully!

In [17]:
sales_df["description"].nunique()

1541

In [18]:
import os

os.path.exists("../exports/clean_sales.csv")

True